# Generated by Django 5.1 on 2024-08-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('record_date', models.DateField(auto_now_add=True)),
                ('outpatient_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lab_number', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('sample_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('loinc_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('long_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('property', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=20, null=True)),
                ('result_interpretation', models.TextField(blank=True, null=True)),
                ('interpretation_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('result_interpretation', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labdata.patient')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labdata.testtype')),
            ],
        ),
    ]
