# Generated by Django 5.1 on 2024-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
