# Generated by Django 5.1 on 2024-08-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0003_alter_patient_firstname_alter_patient_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
